export const SEARCH_BEGIN = 'SEARCH_BEGIN';
export const SEARCH_SUCCESS='SEARCH_SUCCESS';
export const SEARCH_FAILURE='SEARCH_FAILURE'

export const GET_PRODUCTS_BEGIN ='GET_PRODUCTS_BEGIN';
export const GET_PRODUCTS_SUCCESS='GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE='GET_PRODUCTS_FAILURE';

export const AUTH_SIGNUP_SUCCESS='AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP_FAILURE='AUTH_SIGNUP_SUCCESS';

export const AUTH_SIGNIN_BEGIN='AUTH_SIGNIN_BEGIN';
export const AUTH_SIGNIN_SUCCESS='AUTH_SIGNIN_SUCCESS';
export const AUTH_SIGNIN_FAILURE='AUTH_SIGNIN_FAILURE';

export const GET_PRODUCT_SUCCESS='GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILURE='GET_PRODUCT_FAILURE';
