export const SEARCH_BEGIN = 'SEARCH_BEGIN';
export const SEARCH_SUCCESS='SEARCH_SUCCESS';
export const SEARCH_FAILURE='SEARCH_FAILURE'

export const GET_PRODUCTS_BEGIN ='GET_PRODUCTS_BEGIN';
export const GET_PRODUCTS_SUCCESS='GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE='GET_PRODUCTS_FAILURE';
